language: go

install:
  - go get -d -t -v ./... && go build -v ./...

go:
  - 1.10.x

script:
  - go vet ./...
  - ./go.test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "yrank"
  skip_cleanup: true
  on:
    tags: true
